### ISSUE TITLE
Is the etl compatbile with windows

### ISSUE THREAD

**Issue by poupou-web3** [supermodularxyz/grants-etl#4]
I'm getting this issue on Windows when I do `docker-compose`

pgadmin                | postfix/postlog: starting the Postfix mail system
pgadmin                | [2023-07-30 15:59:54 +0000] [1] [INFO] Starting gunicorn 20.1.0
pgadmin                | [2023-07-30 15:59:54 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
pgadmin                | [2023-07-30 15:59:54 +0000] [1] [INFO] Using worker: gthread
pgadmin                | [2023-07-30 15:59:54 +0000] [81] [INFO] Booting worker with pid: 81
pgadmin                | [2023-07-30 15:59:58 +0000] [81] [ERROR] Exception in worker process
pgadmin                | Traceback (most recent call last):
pgadmin                |   File "/venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
pgadmin                |     worker.init_process()
pgadmin                |   File "/venv/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
pgadmin                |     super().init_process()
pgadmin                |   File "/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
pgadmin                |     self.load_wsgi()
pgadmin                |   File "/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
pgadmin                |     self.wsgi = self.app.wsgi()
pgadmin                |                 ^^^^^^^^^^^^^^^
pgadmin                |   File "/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
pgadmin                |     self.callable = self.load()
pgadmin                |                     ^^^^^^^^^^^
pgadmin                |   File "/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
pgadmin                |     return self.load_wsgiapp()
pgadmin                |            ^^^^^^^^^^^^^^^^^^^
pgadmin                |   File "/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
pgadmin                |     return util.import_app(self.app_uri)
pgadmin                |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pgadmin                |   File "/venv/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
pgadmin                |     mod = importlib.import_module(module)
pgadmin                |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pgadmin                |   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
pgadmin                |     return _bootstrap._gcd_import(name[level:], package, level)
pgadmin                |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pgadmin                |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
pgadmin                |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
pgadmin                |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
pgadmin                |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
pgadmin                |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
pgadmin                |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
pgadmin                |   File "/pgadmin4/run_pgadmin.py", line 4, in <module>
pgadmin                |     from pgAdmin4 import app
pgadmin                |   File "/pgadmin4/pgAdmin4.py", line 104, in <module>
pgadmin                |     app = create_app()
pgadmin                |           ^^^^^^^^^^^^
pgadmin                |   File "/pgadmin4/pgadmin/__init__.py", line 477, in create_app
pgadmin                |     run_migration_for_sqlite()
pgadmin                |   File "/pgadmin4/pgadmin/__init__.py", line 452, in run_migration_for_sqlite
pgadmin                |     os.chmod(config.SQLITE_PATH, 0o600)
pgadmin                | PermissionError: [Errno 1] Operation not permitted: '/var/lib/pgadmin/pgadmin4.db'
pgadmin                | [2023-07-30 15:59:58 +0000] [81] [INFO] Worker exiting (pid: 81)
pgadmin                | [2023-07-30 15:59:58 +0000] [1] [INFO] Shutting down: Master
pgadmin                | [2023-07-30 15:59:58 +0000] [1] [INFO] Reason: Worker failed to boot.
pgadmin exited with code 0

**Comment by ghostffcode** [comment]
Yes and no. The previous data cache has `data/pgadmin-data` but there's actually no need to share this directory.
Just pushed an update that removes this and lets you run a clean Docker container that works.

### Steps to fix

- Remove existing container:

```bash
docker compose down
```

- Update your local repo
- Start Docker container:

```bash
docker compose up
```

Visit pgadmin url: `http://localhost:5555`

Everything should work fine now. Thank you for pointing this out

**Comment by poupou-web3** [comment]
It looks like it fix the error but now I can't set up the db connection, attached is a screenshot of pgadmin and the logs when running `docker compose up`
[logs-docker-compose-up.txt](https://github.com/supermodularxyz/grants-etl/files/12226493/logs-docker-compose-up.txt)
![image](https://github.com/supermodularxyz/grants-etl/assets/108153089/af238e36-a151-4b7f-8d9f-907b3fa91a8d)

**Comment by ghostffcode** [comment]
Check your Docker settings to be sure `*.docker.internal` is in your hosts file, see screenshot below:

![docker internal](https://github.com/supermodularxyz/grants-etl/assets/14002941/3dbfe578-4300-4286-9b6b-073f4d84b75f)

**Comment by ghostffcode** [comment]
@poupou-web3 I will be closing this issue since its been resolved. Please let me know if something still fails on your end.
